version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestoque_web
    restart: unless-stopped
    ports:
      - "80:5000"
    env_file:
      - .env
    environment:
      FLASK_APP: run:app
